import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const ENV_PATH = path.join(__dirname, '..', '..', '.env');

export function readEnv(): Record<string, string> {
  const values: Record<string, string> = {};
  try {
    const content = readFileSync(ENV_PATH, 'utf8');
    for (const line of content.split('\n')) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) continue;
      const eqIdx = trimmed.indexOf('=');
      if (eqIdx === -1) continue;
      const key = trimmed.slice(0, eqIdx).trim();
      const val = trimmed.slice(eqIdx + 1).trim();
      values[key] = val;
    }
  } catch { /* file doesn't exist yet */ }
  return values;
}

export function readEnvRedacted(): Record<string, string> {
  const values = readEnv();
  const SECRET_KEYS = ['TELEGRAM_TOKEN', 'SLACK_BOT_TOKEN', 'SLACK_APP_TOKEN', 'GEMINI_API_KEY'];
  const redacted: Record<string, string> = {};
  for (const [key, val] of Object.entries(values)) {
    if (SECRET_KEYS.includes(key) && val.length > 8) {
      redacted[key] = val.slice(0, 4) + '...' + val.slice(-4);
    } else {
      redacted[key] = val;
    }
  }
  return redacted;
}

export function writeEnv(config: Record<string, string>): { success: boolean; path: string } {
  const lines: string[] = [
    '# Generated by bark-pack setup wizard',
    '',
  ];

  // WhatsApp
  lines.push('# WhatsApp');
  lines.push(`WA_ENABLED=${config.WA_ENABLED || 'false'}`);
  if (config.WA_ENABLED === 'true') {
    lines.push(`WA_GROUP=${config.WA_GROUP || 'bark-pack'}`);
    if (config.WA_OWNER) lines.push(`WA_OWNER=${config.WA_OWNER}`);
  }
  lines.push('');

  // Telegram
  lines.push('# Telegram');
  if (config.TELEGRAM_TOKEN) {
    lines.push(`TELEGRAM_TOKEN=${config.TELEGRAM_TOKEN}`);
    if (config.TG_OWNER) lines.push(`TG_OWNER=${config.TG_OWNER}`);
  } else {
    lines.push('# TELEGRAM_TOKEN=');
    lines.push('# TG_OWNER=');
  }
  lines.push('');

  // Slack
  lines.push('# Slack');
  if (config.SLACK_BOT_TOKEN) {
    lines.push(`SLACK_BOT_TOKEN=${config.SLACK_BOT_TOKEN}`);
    if (config.SLACK_APP_TOKEN) lines.push(`SLACK_APP_TOKEN=${config.SLACK_APP_TOKEN}`);
    if (config.SLACK_OWNER) lines.push(`SLACK_OWNER=${config.SLACK_OWNER}`);
  } else {
    lines.push('# SLACK_BOT_TOKEN=');
    lines.push('# SLACK_APP_TOKEN=');
    lines.push('# SLACK_OWNER=');
  }
  lines.push('');

  // Backends
  lines.push('# LLM Backends');
  lines.push(`DEFAULT_BACKEND=${config.DEFAULT_BACKEND || 'claude-code'}`);
  lines.push(`ENABLED_BACKENDS=${config.ENABLED_BACKENDS || 'claude-code'}`);
  lines.push('');

  // Gemini API key
  if (config.GEMINI_API_KEY) {
    lines.push(`GEMINI_API_KEY=${config.GEMINI_API_KEY}`);
    lines.push('');
  }

  // Voice
  lines.push('# Voice transcription (optional)');
  if (config.WHISPER_MODEL) {
    lines.push(`WHISPER_MODEL=${config.WHISPER_MODEL}`);
  } else {
    lines.push('# WHISPER_MODEL=/opt/homebrew/share/whisper-cpp/models/ggml-base.en.bin');
  }
  lines.push('');

  // UI
  lines.push('# UI Dashboard');
  lines.push(`UI_PORT=${config.UI_PORT || '3333'}`);
  lines.push('');

  // Fallback
  lines.push('# Agent Fallback');
  lines.push(`FALLBACK_ENABLED=${config.FALLBACK_ENABLED || 'true'}`);
  lines.push(`AGENT_TIMEOUT=${config.AGENT_TIMEOUT || '600000'}`);
  lines.push(`FALLBACK_MAX_RETRIES=${config.FALLBACK_MAX_RETRIES || '3'}`);
  lines.push(`FALLBACK_BACKOFF_MS=${config.FALLBACK_BACKOFF_MS || '5000,15000,30000'}`);
  lines.push(`FALLBACK_BACKEND_PRIORITY=${config.FALLBACK_BACKEND_PRIORITY || config.ENABLED_BACKENDS || 'claude-code'}`);
  lines.push('');

  // History
  lines.push('# History');
  lines.push(`HISTORY_MAX_TURNS=${config.HISTORY_MAX_TURNS || '10'}`);
  lines.push(`SUMMARY_INTERVAL_TURNS=${config.SUMMARY_INTERVAL_TURNS || '5'}`);
  lines.push('');

  writeFileSync(ENV_PATH, lines.join('\n'));
  return { success: true, path: ENV_PATH };
}
